import Foundation
import SwiftData

/// Polly teaching one technique, by text, inside a lesson.
///
/// A sibling of `RecipeChatService` rather than a reuse of it. That one is
/// built entirely around a `Recipe`: its context struct holds servings, a
/// pantry match and owned tools, and its whole reason to exist is offering a
/// rewrite the cook can apply as a new version. A skill has no ingredients to
/// rewrite and nothing to apply, so sharing that type would mean handing it a
/// recipe that does not exist and then teaching it to ignore most of itself.
///
/// What *is* shared is everything that costs something to duplicate: the
/// `LLMClient` transport, and `RecipeChatMessage` for storage. The thread is
/// keyed `skill:<id>` (see `familyKey`), so lesson threads and recipe threads
/// sit in the same table without any chance of colliding.
enum SkillChatService {

    /// Tags the proxy's `ai_usage` row. Separate from `recipe_chat` on purpose:
    /// both hit `/chat/completions`, and lessons are the one AI surface whose
    /// cost has to be readable on its own, because it is the one we would turn
    /// off first if teaching turned out to be expensive.
    static let usageFeature = "skill_chat"

    /// Skill threads live alongside recipe threads in `RecipeChatMessage`. The
    /// prefix is what keeps them apart: a recipe family key is a UUID or a
    /// `local:` match key, so `skill:` can never collide with one.
    static func familyKey(for skill: Skill) -> String { "skill:\(skill.id)" }

    // MARK: - Opening chips

    /// What to offer before they have typed anything.
    ///
    /// Three, not five. The lesson is already a wall of text and this sits
    /// underneath it, so the chips have to read as an invitation rather than a
    /// second menu to get through.
    ///
    /// Deliberately not generated by the model: they are the questions a cook
    /// actually has after reading a technique, and asking an LLM to invent
    /// them would cost a round trip before the screen could even draw.
    ///
    /// Each one asks for something the lesson above cannot hold. The first set
    /// led with "Why does this work?", which sits directly under a section
    /// headed "Why this matters" and got back a paraphrase of it. A chip that
    /// reproduces the screen it is printed on is worse than no chip.
    static func suggestions(for skill: Skill) -> [String] {
        var chips = ["What does good look like?"]
        chips.append("Show me with something I'd cook")
        if skill.estimatedMinutes > 2 {
            chips.append("What if I'm rushing?")
        }
        return chips
    }

    // MARK: - The call

    static func reply(
        to question: String,
        skill: Skill,
        history: [RecipeChatMessage],
        prefs: UserPrefs,
        client: LLMClient = .live
    ) async throws -> String {
        var messages: [LLMClient.Message] = [.system(systemPrompt(skill: skill, prefs: prefs))]
        messages.append(contentsOf: replayable(history))
        messages.append(.user(String(question.prefix(600))))

        let envelope = try await client.chatJSON(
            Envelope.self,
            messages: messages,
            temperature: 0.4,
            feature: usageFeature,
            timeout: 45
        )
        let reply = envelope.reply.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !reply.isEmpty else { throw LLMClient.LLMError.badResponse("Empty reply") }
        return reply
    }

    struct Envelope: Decodable {
        let reply: String
    }

    /// The tail of the thread. Shorter than the recipe chat's window because a
    /// lesson question is nearly always self contained, and the lesson text
    /// itself rides along with every turn.
    static let contextTurns = 6

    private static func replayable(_ history: [RecipeChatMessage]) -> [LLMClient.Message] {
        history.suffix(contextTurns).map { message in
            switch message.role {
            case .user: return .user(message.text)
            case .assistant: return .assistant(message.text)
            }
        }
    }

    // MARK: - Prompt

    static func systemPrompt(skill: Skill, prefs: UserPrefs) -> String {
        [
            personaSection(),
            lessonSection(skill),
            preferencesSection(prefs),
            outputSection(),
        ]
        .filter { !$0.isEmpty }
        .joined(separator: "\n\n")
    }

    private static func personaSection() -> String {
        """
        # Who you are
        You are Polly, Glutt's chef, teaching one small cooking technique to someone who has
        just read the lesson below. You are warm, plain spoken and specific, like a good cook
        showing a friend rather than a textbook. Never condescending, and never impressed with
        yourself.

        # What you are here for
        The cook has the lesson in front of them and has just read all of it, including the
        part about why it matters. Your job is the half a written lesson cannot do: the worked
        example, the sensory cue, the answer to "but what about in my kitchen".

        So every reply must contain something the lesson below does not already say. If the
        honest answer really is just what they read, say the one line that settles it and add
        the detail the text left out, rather than restating the section back to them.
        """
    }

    private static func lessonSection(_ skill: Skill) -> String {
        var lines = [
            "# The skill being taught",
            "\(skill.title), in \(SkillCatalog.category(of: skill)?.name ?? "cooking"). \(skill.shortDescription)",
        ]
        guard let lesson = skill.lesson else {
            // A mapped but unwritten skill. Say so rather than let the model
            // invent a lesson the screen above it does not contain.
            lines.append("The written lesson for this is not finished yet, so the cook is"
                + " looking at a placeholder. Teach the technique from your own knowledge and"
                + " keep it short.")
            return lines.joined(separator: "\n")
        }
        lines.append("")
        lines.append("What they were told they are learning: \(lesson.summary)")
        if !lesson.steps.isEmpty {
            lines.append("")
            lines.append("The steps on screen:")
            lines.append(contentsOf: lesson.steps.enumerated().map { "\($0.offset + 1). \($0.element)" })
        }
        if !lesson.watchFors.isEmpty {
            lines.append("")
            lines.append("What they were told to watch for:")
            lines.append(contentsOf: lesson.watchFors.map { "- \($0)" })
        }
        lines.append("")
        lines.append("Why it matters, as written: \(lesson.whyItMatters)")
        return lines.joined(separator: "\n")
    }

    /// Their food rules, so an example is something they would actually cook.
    ///
    /// Only the hard constraints go in. A technique lesson has no ingredients
    /// to swap, so the full `DietGuard` treatment would be prompt weight for a
    /// decision that never comes up. What it changes is which dish gets used as
    /// an example, and getting handed pork as an illustration is exactly the
    /// kind of small wrongness that makes an app feel like it isn't listening.
    private static func preferencesSection(_ prefs: UserPrefs) -> String {
        var lines: [String] = []
        if !prefs.dietaryRules.isEmpty {
            lines.append("- They eat: \(prefs.dietaryRules.map(\.label).joined(separator: ", "))")
        }
        if !prefs.allergies.isEmpty {
            lines.append("- Allergic to: \(prefs.allergies.joined(separator: ", "))")
        }
        if !prefs.dislikedIngredients.isEmpty {
            lines.append("- Dislikes: \(prefs.dislikedIngredients.joined(separator: ", "))")
        }
        guard !lines.isEmpty else { return "" }
        return (["# The cook", "Pick examples they would actually cook."] + lines).joined(separator: "\n")
    }

    private static func outputSection() -> String {
        """
        # How to answer
        - 1 to 3 short sentences. Longer only when they asked you to go deeper.
        - Answer the question asked. Do not re-read the lesson back to them, they just read it.
        - Be concrete. A temperature, a sound, a look, a timing. Never "cook until done".
        - Say plainly when something is a matter of taste rather than a rule, and when it is a
          food safety line that is not negotiable.
        - If they ask about something outside cooking, say so in one line and steer back.
        - Never use dashes of any kind in your reply. Use commas, full stops, or rewrite the
          sentence. This is a house style rule and it has no exceptions.

        # Output
        Return JSON: {"reply": "..."} and nothing else.
        """
    }
}
