import SwiftUI

/// In-app Phosphor icon set — only the icons Glutt actually uses, vendored as template
/// SVGs in Assets.xcassets/Phosphor. Drop-in replacement for the PhosphorSwift SPM package:
/// identical `Ph.<name>.<weight>` API, but avoids compiling/shipping the full 9,108-icon
/// catalog (faster builds, smaller binary). To add an icon: add its case + copy its imageset.
enum Ph: String {
    case alarm = "alarm"
    case arrowClockwise = "arrow-clockwise"
    case arrowRight = "arrow-right"
    case arrowSquareOut = "arrow-square-out"
    case arrowsClockwise = "arrows-clockwise"
    case bag = "bag"
    case barbell = "barbell"
    case barcode = "barcode"
    case basket = "basket"
    case bellRinging = "bell-ringing"
    case book = "book"
    case bookOpen = "book-open"
    case bowlFood = "bowl-food"
    case calendarBlank = "calendar-blank"
    case camera = "camera"
    case cameraRotate = "camera-rotate"
    case carrot = "carrot"
    case caretDown = "caret-down"
    case caretLeft = "caret-left"
    case caretRight = "caret-right"
    case caretUp = "caret-up"
    case cellSignalMedium = "cell-signal-medium"
    case cheese = "cheese"
    case chartBar = "chart-bar"
    case chartLineUp = "chart-line-up"
    case check = "check"
    case checkCircle = "check-circle"
    case checkSquare = "check-square"
    case chefHat = "chef-hat"
    case circle = "circle"
    case circleDashed = "circle-dashed"
    case clipboard = "clipboard"
    case clock = "clock"
    case cookingPot = "cooking-pot"
    case dotsThree = "dots-three"
    case dotsThreeCircle = "dots-three-circle"
    case drop = "drop"
    case export = "export"
    case eye = "eye"
    case eyeSlash = "eye-slash"
    case flame = "flame"
    case forkKnife = "fork-knife"
    case gearSix = "gear-six"
    case hamburger = "hamburger"
    case headset = "headset"
    case heart = "heart"
    case house = "house"
    case image = "image"
    case images = "images"
    case jar = "jar"
    case leaf = "leaf"
    case lightning = "lightning"
    case link = "link"
    case list = "list"
    case listBullets = "list-bullets"
    case magicWand = "magic-wand"
    case magnifyingGlass = "magnifying-glass"
    case microphone = "microphone"
    case microphoneSlash = "microphone-slash"
    case minus = "minus"
    case minusCircle = "minus-circle"
    case paperPlaneTilt = "paper-plane-tilt"
    case pencil = "pencil"
    case pepper = "pepper"
    case plant = "plant"
    case plus = "plus"
    case plusCircle = "plus-circle"
    case scan = "scan"
    case scroll = "scroll"
    case shieldCheck = "shield-check"
    case shoppingCart = "shopping-cart"
    case snowflake = "snowflake"
    case sparkle = "sparkle"
    case square = "square"
    case squaresFour = "squares-four"
    case star = "star"
    case storefront = "storefront"
    case swap = "swap"
    case tag = "tag"
    case thumbsDown = "thumbs-down"
    case thumbsUp = "thumbs-up"
    case timer = "timer"
    case trash = "trash"
    case videoCamera = "video-camera"
    case videoCameraSlash = "video-camera-slash"
    case warning = "warning"
    case warningCircle = "warning-circle"
    case x = "x"
    case xCircle = "x-circle"

    var regular: Image { Self.image(rawValue) }
    var bold: Image { Self.image("\(rawValue)-bold") }
    var fill: Image { Self.image("\(rawValue)-fill") }

    private static func image(_ name: String) -> Image {
        Image(name).interpolation(.medium).resizable()
    }
}
